export const CAVE_MIND_CONFIG = {
    salience: {
        decay: 0.82,
        appear: 0.65,
        moveScale: 0.01,
        selectedImpulse: 0.85,
        draggedImpulse: 1.1,
        assignmentImpulse: 0.35,
        absorptionImpulse: 0.3,
        cycleImpulse: 0.4,
        selectedBonus: 0.5,
        draggedBonus: 1.2,
        assignmentBonus: 0.2,
        absorptionBonus: 0.28,
        cycleActiveBonus: 0.08,
        nearingBonus: 0.42,
        effortBonus: 0.25,
        nearCompleteThreshold: 0.78,
        focusCeiling: 2.8,
        hysteresisMargin: 0.18,
        multipliers: {
            selected: 1.15,
            dragged: 1.25,
            assignment: 1.08,
            absorption: 1.1,
            exploration: 1.06,
        },
    },
    emotions: {
        decay: 0.88,
        curiosityDecay: 0.8,
        comfortRiseThreshold: 0.12,
        baselines: {
            happiness: 0.061,
            sadness: 0.06,
            terror: 0.07,
            curiosity: 0.08,
        },
        worry: {
            sampleWindowSeconds: 5,
            fillPerDeclineTick: 0.18,
            quickDeclinePenalty: 1.4,
            prolongedDeclinePenaltyPerTick: 0.08,
            recoveryPerComfortRise: 6.5,
            trendEpsilon: 0.01,
            comfortReliefFloor: 0.9,
            comfortReliefPerTick: 0.24,
        },
        curiosityBoredom: {
            gainPerContributingTick: 0.2,
            recoveryPerTick: 0.12,
        },
        impulses: {
            comfortRise: 0.18,
            absorptionComplete: 0.16,
            purgeBeganTerror: 0.48,
            purgeBeganCuriosity: 0.14,
            purgeKill: 0.22,
            butchered: 0.24,
            xpGain: 0.12,
            levelGain: 0.24,
            firstCycle: 0.14,
        },
    },
    lookMode: {
        strongFocus: 0.62,
        panicTerror: 0.55,
        lockTerror: 0.72,
        inspectCuriosity: 0.5,
    },
    pulse: {
        terror: "panic",
        sadness: "frozen",
        uplift: "healthy",
        terrorThreshold: 0.55,
        sadnessThreshold: 0.5,
        upliftThreshold: 0.6,
    },
} as const;
