import { AppTheme } from "./types";
import { GAME_PALETTE } from "../../../../game/palette/gamePalette";
import {
    typography,
    zIndex,
    spacing,
    borderRadius,
    fontSize,
    iconSize,
    borderWidth,
    sizes,
} from "./tokens";

export const defaultTheme: AppTheme = {
    colors: {
        background: GAME_PALETTE.surfaces.background,
        surface: GAME_PALETTE.surfaces.panel,
        surfaceHighlight: GAME_PALETTE.surfaces.panelHighlight,
        modal: GAME_PALETTE.surfaces.modal,
        text: GAME_PALETTE.text.primary,
        secondary: GAME_PALETTE.text.secondary,
        primary: GAME_PALETTE.interactive.primary,
        selected: GAME_PALETTE.interactive.selected,
        disabled: GAME_PALETTE.interactive.disabled,
        danger: GAME_PALETTE.interactive.danger,
        success: GAME_PALETTE.interactive.success,
        error: GAME_PALETTE.interactive.danger,
        buttonDefault: GAME_PALETTE.interactive.buttonDefault,
        buttonSelected: GAME_PALETTE.interactive.buttonSelected,
        stamina: GAME_PALETTE.mechanics.stamina,
        xp: GAME_PALETTE.mechanics.xp,
        activity: GAME_PALETTE.mechanics.activity,
        understanding: GAME_PALETTE.mechanics.understanding,
        heat: GAME_PALETTE.mechanics.heat,
        food: GAME_PALETTE.mechanics.food,
        goal: GAME_PALETTE.mechanics.goal,
        severity: GAME_PALETTE.severity,
        purgeAlarm: GAME_PALETTE.purgeAlarm,
        statusKeywordHungry: GAME_PALETTE.statusKeywords.hungry,
        statusKeywordCold: GAME_PALETTE.statusKeywords.cold,
        scrollbarThumb: GAME_PALETTE.surfaces.scrollbarThumb,
        scrollbarThumbHover: GAME_PALETTE.surfaces.scrollbarThumbHover,
        whiteBorderSubtle: GAME_PALETTE.chrome.whiteBorderSubtle,
        whiteBorderMedium: GAME_PALETTE.chrome.whiteBorderMedium,
        blackShadow: GAME_PALETTE.chrome.blackShadow,
    },
    fonts: {
        observer: typography.crimson,
        scientist: typography.inter,
        ui: typography.crimson,
        code: typography.courier,
    },
    zIndices: {
        base: zIndex.base,
        foreground: zIndex.foreground,
        modal: zIndex.modal,
        float: zIndex.float,
        toast: zIndex.toast,
        tooltip: zIndex.tooltip,
        callout: zIndex.callout,
    },
    spacing: spacing,
    radius: borderRadius,
    fontSize: fontSize,
    iconSize: iconSize,
    borderWidth: borderWidth,
    sizes: sizes,
};

