export const DISPLAY_IMAGE_CANVAS_SIZE = 128;
export const DISPLAY_IMAGE_CANVAS_CENTER = DISPLAY_IMAGE_CANVAS_SIZE / 2;
export const RESOLVED_DISPLAY_ICON_RADIUS = 60;
export const RESOLVED_DISPLAY_PREVIEW_ENTITY_ID = "__display_preview__";
export const RESOLVED_DISPLAY_STATIC_TIME_MS = 0;
export const RESOLVED_DISPLAY_STATIC_PULSE_VALUE = 0;
